In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score
from imblearn.over_sampling import RandomOverSampler, SMOTE
from sklearn.ensemble import RandomForestClassifier

In [2]:
strokeData = pd.read_csv("..\..\data\cleaned\cleanedDataset.csv")
X = strokeData.drop(columns='stroke', axis=1)
y = strokeData['stroke']

In [3]:
def rf_SMOTE70():
    # splitting 70-30
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

    # oversampling minority class
    oversample = SMOTE()
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Random Forest
    rf = RandomForestClassifier(n_estimators=10, min_samples_leaf=34)

    # fit rf into oversampled training set
    rf.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = rf.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Random Forest Oversampling Recall Rate: {recall*100:.2f}%')

In [5]:
rf_SMOTE70()

1    3403
0    3403
Name: stroke, dtype: int64
0    1458
1      75
Name: stroke, dtype: int64
[[1417   41]
 [  66    9]]
              precision    recall  f1-score   support

    noStroke       0.96      0.97      0.96      1458
      stroke       0.18      0.12      0.14        75

    accuracy                           0.93      1533
   macro avg       0.57      0.55      0.55      1533
weighted avg       0.92      0.93      0.92      1533

0.12
Random Forest Oversampling Recall Rate: 12.00%


In [12]:
def rf_SMOTE80():
    # splitting 80-20
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # oversampling minority class
    oversample = SMOTE()
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Random Forest
    rf = RandomForestClassifier(n_estimators=10, min_samples_leaf=34)

    # fit rf into oversampled training set
    rf.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = rf.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Random Forest Oversampling Recall Rate: {recall*100:.2f}%')

In [116]:
rf_SMOTE80()

1    3889
0    3889
Name: stroke, dtype: int64
0    972
1     50
Name: stroke, dtype: int64
[[958  14]
 [ 43   7]]
              precision    recall  f1-score   support

    noStroke       0.96      0.99      0.97       972
      stroke       0.33      0.14      0.20        50

    accuracy                           0.94      1022
   macro avg       0.65      0.56      0.58      1022
weighted avg       0.93      0.94      0.93      1022

0.14
Random Forest Oversampling Recall Rate: 14.00%


In [73]:
def rf_SMOTE90():
    # splitting 90-10
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

    # oversampling minority class
    oversample = SMOTE()
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Random Forest
    rf = RandomForestClassifier(n_estimators=10, min_samples_leaf=34)

    # fit rf into oversampled training set
    rf.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = rf.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Random Forest Oversampling Recall Rate: {recall*100:.2f}%')

In [87]:
rf_SMOTE90()

1    4375
0    4375
Name: stroke, dtype: int64
0    486
1     25
Name: stroke, dtype: int64
[[473  13]
 [ 20   5]]
              precision    recall  f1-score   support

    noStroke       0.96      0.97      0.97       486
      stroke       0.28      0.20      0.23        25

    accuracy                           0.94       511
   macro avg       0.62      0.59      0.60       511
weighted avg       0.93      0.94      0.93       511

0.2
Random Forest Oversampling Recall Rate: 20.00%
