In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score
from imblearn.over_sampling import RandomOverSampler, SMOTE
from sklearn.tree import DecisionTreeClassifier

In [3]:
strokeData = pd.read_csv("..\..\data\cleaned\cleanedDataset.csv")
X = strokeData.drop(columns='stroke', axis=1)
y = strokeData['stroke']

In [ ]:
def dt_ROS70():
    # splitting 70-30
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

    # oversampling minority class
    oversample = RandomOverSampler(sampling_strategy='minority')
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Decision Trees
    dt = DecisionTreeClassifier()

    # fit dt into oversampled training set
    dt.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = dt.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Decision Trees Oversampling Recall Rate: {recall*100:.2f}%')

In [4]:
dt_ROS70()

1    3403
0    3403
Name: stroke, dtype: int64
0    1458
1      75
Name: stroke, dtype: int64
[[1406   52]
 [  66    9]]
              precision    recall  f1-score   support

    noStroke       0.96      0.96      0.96      1458
      stroke       0.15      0.12      0.13        75

    accuracy                           0.92      1533
   macro avg       0.55      0.54      0.55      1533
weighted avg       0.92      0.92      0.92      1533

0.12
Decision Trees Oversampling Recall Rate: 12.00%


In [5]:
def dt_ROS80():
    # splitting 80-20
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # oversampling minority class
    oversample = RandomOverSampler(sampling_strategy='minority')
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Decision Trees
    dt = DecisionTreeClassifier()

    # fit dt into oversampled training set
    dt.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = dt.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Decision Trees Oversampling Recall Rate: {recall*100:.2f}%')

In [6]:
dt_ROS80()

1    3889
0    3889
Name: stroke, dtype: int64
0    972
1     50
Name: stroke, dtype: int64
[[942  30]
 [ 46   4]]
              precision    recall  f1-score   support

    noStroke       0.95      0.97      0.96       972
      stroke       0.12      0.08      0.10        50

    accuracy                           0.93      1022
   macro avg       0.54      0.52      0.53      1022
weighted avg       0.91      0.93      0.92      1022

0.08
Decision Trees Oversampling Recall Rate: 8.00%


In [7]:
def dt_ROS90():
    # splitting 90-10
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

    # oversampling minority class
    oversample = RandomOverSampler(sampling_strategy='minority')
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Decision Trees
    dt = DecisionTreeClassifier()

    # fit dt into oversampled training set
    dt.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = dt.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Decision Trees Oversampling Recall Rate: {recall*100:.2f}%')

In [8]:
dt_ROS90()

1    4375
0    4375
Name: stroke, dtype: int64
0    486
1     25
Name: stroke, dtype: int64
[[475  11]
 [ 24   1]]
              precision    recall  f1-score   support

    noStroke       0.95      0.98      0.96       486
      stroke       0.08      0.04      0.05        25

    accuracy                           0.93       511
   macro avg       0.52      0.51      0.51       511
weighted avg       0.91      0.93      0.92       511

0.04
Decision Trees Oversampling Recall Rate: 4.00%
