In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score
from imblearn.over_sampling import RandomOverSampler, SMOTE
from sklearn.neural_network import MLPClassifier

In [2]:
strokeData = pd.read_csv("..\..\data\cleaned\cleanedDataset.csv")
X = strokeData.drop(columns='stroke', axis=1)
y = strokeData['stroke']

In [3]:
def nn_SMOTE70():
    # splitting 70-30
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

    # oversampling minority class
    oversample = SMOTE()
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Neural Networks
    nn = MLPClassifier(max_iter=1000)

    # fit nn into oversampled training set
    nn.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = nn.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Neural Networks Oversampling Recall Rate: {recall*100:.2f}%')

In [6]:
nn_SMOTE70()

1    3403
0    3403
Name: stroke, dtype: int64
0    1458
1      75
Name: stroke, dtype: int64
[[1114  344]
 [  28   47]]
              precision    recall  f1-score   support

    noStroke       0.98      0.76      0.86      1458
      stroke       0.12      0.63      0.20        75

    accuracy                           0.76      1533
   macro avg       0.55      0.70      0.53      1533
weighted avg       0.93      0.76      0.82      1533

0.6266666666666667
Neural Networks Oversampling Recall Rate: 62.67%


In [7]:
def nn_SMOTE80():
    # splitting 80-20
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # oversampling minority class
    oversample = SMOTE()
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Neural Networks
    nn = MLPClassifier(max_iter=1000)

    # fit nn into oversampled training set
    nn.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = nn.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Neural Networks Oversampling Recall Rate: {recall*100:.2f}%')

In [9]:
nn_SMOTE80()

1    3889
0    3889
Name: stroke, dtype: int64
0    972
1     50
Name: stroke, dtype: int64
[[705 267]
 [ 18  32]]
              precision    recall  f1-score   support

    noStroke       0.98      0.73      0.83       972
      stroke       0.11      0.64      0.18        50

    accuracy                           0.72      1022
   macro avg       0.54      0.68      0.51      1022
weighted avg       0.93      0.72      0.80      1022

0.64
Neural Networks Oversampling Recall Rate: 64.00%


In [10]:
def nn_SMOTE90():
    # splitting 90-10
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

    # oversampling minority class
    oversample = SMOTE()
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Neural Networks
    nn = MLPClassifier(max_iter=1000)

    # fit nn into oversampled training set
    nn.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = nn.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Neural Networks Oversampling Recall Rate: {recall*100:.2f}%')

In [13]:
nn_SMOTE90()

1    4375
0    4375
Name: stroke, dtype: int64
0    486
1     25
Name: stroke, dtype: int64
[[356 130]
 [ 12  13]]
              precision    recall  f1-score   support

    noStroke       0.97      0.73      0.83       486
      stroke       0.09      0.52      0.15        25

    accuracy                           0.72       511
   macro avg       0.53      0.63      0.49       511
weighted avg       0.92      0.72      0.80       511

0.52
Neural Networks Oversampling Recall Rate: 52.00%
