In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score
from imblearn.over_sampling import RandomOverSampler, SMOTE
from sklearn.svm import SVC

In [2]:
strokeData = pd.read_csv("..\..\data\cleaned\cleanedDataset.csv")
X = strokeData.drop(columns='stroke', axis=1)
y = strokeData['stroke']

In [3]:
def svm_ROS70():
    # splitting 70-30
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

    # oversampling minority class
    oversample = RandomOverSampler(sampling_strategy='minority')
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Support Vector Machine
    svm = SVC(kernel='linear')

    # fit svm into oversampled training set
    svm.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = svm.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Support Vector Machine Oversampling Recall Rate: {recall*100:.2f}%')

In [4]:
svm_ROS70()

1    3403
0    3403
Name: stroke, dtype: int64
0    1458
1      75
Name: stroke, dtype: int64
[[1038  420]
 [  15   60]]
              precision    recall  f1-score   support

    noStroke       0.99      0.71      0.83      1458
      stroke       0.12      0.80      0.22        75

    accuracy                           0.72      1533
   macro avg       0.56      0.76      0.52      1533
weighted avg       0.94      0.72      0.80      1533

0.8
Support Vector Machine Oversampling Recall Rate: 80.00%


In [5]:
def svm_ROS80():
    # splitting 80-20
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # oversampling minority class
    oversample = RandomOverSampler(sampling_strategy='minority')
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Support Vector Machine
    svm = SVC(kernel='linear')

    # fit svm into oversampled training set
    svm.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = svm.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Support Vector Machine Oversampling Recall Rate: {recall*100:.2f}%')

In [6]:
svm_ROS80()

1    3889
0    3889
Name: stroke, dtype: int64
0    972
1     50
Name: stroke, dtype: int64
[[704 268]
 [ 10  40]]
              precision    recall  f1-score   support

    noStroke       0.99      0.72      0.84       972
      stroke       0.13      0.80      0.22        50

    accuracy                           0.73      1022
   macro avg       0.56      0.76      0.53      1022
weighted avg       0.94      0.73      0.81      1022

0.8
Support Vector Machine Oversampling Recall Rate: 80.00%


In [7]:
def svm_ROS90():
    # splitting 90-10
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

    # oversampling minority class
    oversample = RandomOverSampler(sampling_strategy='minority')
    X_oversample, y_oversample = oversample.fit_resample(X_train, y_train)
    # checking oversampling counts
    print(y_oversample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Support Vector Machine
    svm = SVC(kernel='linear')

    # fit svm into oversampled training set
    svm.fit(X_oversample, y_oversample)

    # predict labels of oversampled test dataset
    y_pred = svm.predict(X_test)

    # compute and print oversampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print oversampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Support Vector Machine Oversampling Recall Rate: {recall*100:.2f}%')

In [8]:
svm_ROS90()

1    4375
0    4375
Name: stroke, dtype: int64
0    486
1     25
Name: stroke, dtype: int64
[[360 126]
 [  8  17]]
              precision    recall  f1-score   support

    noStroke       0.98      0.74      0.84       486
      stroke       0.12      0.68      0.20        25

    accuracy                           0.74       511
   macro avg       0.55      0.71      0.52       511
weighted avg       0.94      0.74      0.81       511

0.68
Support Vector Machine Oversampling Recall Rate: 68.00%
