In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, recall_score
from imblearn.under_sampling import RandomUnderSampler
from sklearn.neural_network import MLPClassifier

In [2]:
strokeData = pd.read_csv("..\..\data\cleaned\cleanedDataset.csv")
X = strokeData.drop(columns='stroke', axis=1)
y = strokeData['stroke']

In [3]:
def nn_RUS70():
    # splitting 70-30
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

    # undersampling majority class
    undersample = RandomUnderSampler(sampling_strategy='majority')
    X_undersample, y_undersample = undersample.fit_resample(X_train, y_train)
    # checking undersampled counts
    print(y_undersample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Neural Networks
    nn = MLPClassifier(max_iter=1000)

    # fit nn into undersampled training set
    nn.fit(X_undersample, y_undersample)

    # predict labels of undersampled test dataset
    y_pred = nn.predict(X_test)

    # compute and print undersampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print undersampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Neural Networks Undersampling Recall Rate: {recall*100:.2f}%')

In [4]:
nn_RUS70()

1    174
0    174
Name: stroke, dtype: int64
0    1458
1      75
Name: stroke, dtype: int64
[[955 503]
 [ 13  62]]
              precision    recall  f1-score   support

    noStroke       0.99      0.66      0.79      1458
      stroke       0.11      0.83      0.19        75

    accuracy                           0.66      1533
   macro avg       0.55      0.74      0.49      1533
weighted avg       0.94      0.66      0.76      1533

0.8266666666666667
Neural Networks Undersampling Recall Rate: 82.67%


In [5]:
def nn_RUS80():
    # splitting 80-20
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # undersampling majority class
    undersample = RandomUnderSampler(sampling_strategy='majority')
    X_undersample, y_undersample = undersample.fit_resample(X_train, y_train)
    # checking undersampled counts
    print(y_undersample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Neural Networks
    nn = MLPClassifier(max_iter=1000)

    # fit nn into undersampled training set
    nn.fit(X_undersample, y_undersample)

    # predict labels of undersampled test dataset
    y_pred = nn.predict(X_test)

    # compute and print undersampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print undersampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Neural Networks Undersampling Recall Rate: {recall*100:.2f}%')

In [11]:
nn_RUS80()

1    199
0    199
Name: stroke, dtype: int64
0    972
1     50
Name: stroke, dtype: int64
[[663 309]
 [  9  41]]
              precision    recall  f1-score   support

    noStroke       0.99      0.68      0.81       972
      stroke       0.12      0.82      0.21        50

    accuracy                           0.69      1022
   macro avg       0.55      0.75      0.51      1022
weighted avg       0.94      0.69      0.78      1022

0.82
Neural Networks Undersampling Recall Rate: 82.00%


In [7]:
def nn_RUS90():
    # splitting 90-10
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

    # undersampling majority class
    undersample = RandomUnderSampler(sampling_strategy='majority')
    X_undersample, y_undersample = undersample.fit_resample(X_train, y_train)
    # checking undersampled counts
    print(y_undersample.value_counts())
    # checking testing counts
    print(y_test.value_counts())

    # create Classifier for Neural Networks
    nn = MLPClassifier(max_iter=1000)

    # fit nn into undersampled training set
    nn.fit(X_undersample, y_undersample)

    # predict labels of undersampled test dataset
    y_pred = nn.predict(X_test)

    # compute and print undersampled confusion matrix
    print(confusion_matrix(y_test, y_pred))
    # compute and print undersampled classification report
    print(classification_report(y_test, y_pred, target_names=['noStroke', 'stroke']))

    # print recall rate (metric we are looking at)
    recall = recall_score(y_test, y_pred)
    print(recall)
    print(f'Neural Networks Undersampling Recall Rate: {recall*100:.2f}%')

In [8]:
nn_RUS90()

1    224
0    224
Name: stroke, dtype: int64
0    486
1     25
Name: stroke, dtype: int64
[[329 157]
 [  8  17]]
              precision    recall  f1-score   support

    noStroke       0.98      0.68      0.80       486
      stroke       0.10      0.68      0.17        25

    accuracy                           0.68       511
   macro avg       0.54      0.68      0.49       511
weighted avg       0.93      0.68      0.77       511

0.68
Neural Networks Undersampling Recall Rate: 68.00%
